### ISSUE TITLE
[Outlaw] Blunderbuss Icon re-appearing

### ISSUE THREAD

**Issue by starl1te** [SimCMinMax/AethysRotation#59] opened 2017-10-15 22:47 UTC
Blunderbuss Icon was previously removed since it looks exactly like Between the Eyes and serves no purpose (Pistol Shot icon is used for all procs, blunderbuss or not)

It's been randomly re-appearing for me and driving me crazy - and when it does, it appears even for regular pistol shot opportunity procs. I finally managed to replicate this on target dummies, and it seems to involve changing equipment sets. if I change between sets with various combinations of Greenskins / Ravenholdt ring / Mantle (going OOC and then attacking the dummies), it will often cause this error, and the only way to revert to normal Pistol Shot icons is keep changing armor sets and (sometimes) reloadui. super annoying in M+

happens in all versions of addon and with no other addons loaded. Hopefully someone can replicate this.

**Comment by Aethys256** [comment] 2017-10-15 22:52
Hmm, I'll try to reproduce it.
If you have more infos do not hesitate.

**Comment by Aethys256** [comment] 2017-10-15 22:56
I found it :)

**Comment by Aethys256** [comment] 2017-10-15 22:57
Fixed in https://github.com/SimCMinMax/AethysRotation/commit/f7b26bdd6561486fedcb61cb0bcc985093c5f164 :)
Long explanation:
  Textures are cached after the first use, that's why. That should fix your issue. Let me know if it's still not the case.

**Comment by starl1te** [comment] 2017-10-16 02:20
thank you. problem remains sadly. before filling out my report I actually found the same thing you changed (I think - the only mention of "cast blunderbuss" i could find) and commented it out, but it didnt work.

to reiterate: outlaw rotation normally works great, red pistol shot icon appears when appropriate. sometimes for me the damn blunderbuss icon starts appearing, and when it does it completely replaces the pistol shot icon (ie its there for all opportunity procs, even the non-blunderbuss ones). the red pistol shot icon never appears. the only way to go back to the normal pistol shot icon is multiple armor set changes / reload /log out.

right now with no other addons and aethys settings at default i attack the target dummy with 4pc and mantle/ring and it works fine. I go ooc swap to 4pc and mantle/greenskin's and attack dummy again and i get blunderbuss. if i swap armor sets again a few times it starts working properly again. this happens with all kinds of equipment changes involving legendaries.  this also happens in mythic dungeons / world quests / etc.

what it looks like. even though only the regular pistol shot oppo proc is up, the blunderbuss icon is suggested.

https://i.imgur.com/k7ciDBZ.jpg

thanks for the wonderful addon btw its been a lifesaver for me.

**Comment by Aethys256** [comment] 2017-10-16 06:15
I thought it would be some blunderbuss texture caching but looks like it is not.
Well, I don't have Greenskins to test (could try on PTR tho) but is Blunderbuss proc when you swap equipment ?

**Comment by ghr74** [comment] 2017-10-31 15:40
Should be fixed in https://github.com/SimCMinMax/AethysRotation/commit/bd136d746396838d107bb23d0e31f36b7870723b , let us know if not.

**Closed by ghr74** 2017-10-31 15:40 UTC
Labels: Bug
